theme: minima  # Minima provides clean layout customization.

title: Tilt-In-Space Wheelchair


header_pages:
  - index.md
  - photos.md
  - requirements.md
  - architecture.md
  - design.md
  - conclusion.md
