theme: minima  # Minima provides clean layout customization.

title: Tilt-In-Space Wheelchair
description: Created for Kyaro Assistive Technologies

header_pages:
  - index.md
  - photos.md
  - requirements.md
  - architecture.md
  - design.md
  - bom.md
  - conclusion.md
